/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GeneticAlgorithm;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingConstants;

/**
 *
 * @author Sage Ralph <SageJeanRalph@Gmail.com>
 */
public class GUI extends javax.swing.JFrame {

private static javax.swing.JTextArea output;
private static final long serialVersionUID = 1L;
/**
 * Creates new form GUI
 */
public GUI() {
    initComponents();
    output = tbOutput;
    inMutationChance.setHorizontalAlignment(SwingConstants.RIGHT);
    
}

public static void output(String text) {
    output.append(text);
}

public void run() throws InterruptedException {
    try {
        if (validInputs()) {
            // Set params
            Main.elitism = (int) inElitism.getValue();
            Main.maxGenerations = (int) inMaxGen.getValue();
            Main.populationSize = (int) inPopSize.getValue();
            Main.runCount = (int) inRunCount.getValue();
            Main.threadCount = (int) inThreadCount.getValue();
            Main.rangeMin = (int) inRangeMin.getValue();
            Main.rangeMax = (int) inRangeMax.getValue();
            Main.mutationChance = Double.parseDouble(inMutationChance.getText());
            Main.sigmaScaling = cbSigmaScaling.isSelected();
            Main.fitnessFunction = tbFitnessFunction.getText();
            Main.genDetail = cbGenDetail.isSelected();
            Main.genSummary = cbGenSummary.isSelected();
            Main.runSummary = cbRunSummary.isSelected();
            Main.allowKnownSolution = cbKnownMax.isSelected();
            Main.knownMax = Double.parseDouble(inMax.getText());
            Main.knownMin = cbKnownMin.isSelected() // 0 if unchecked
                    ? Double.parseDouble(inMin.getText()) : 0;

            // Run
            Main.simulate();
        }
    } catch (Error e) {
        output("Invalid inputs");
    }
}

private boolean validInputs() {
    return true;
}

/**
 * This method is called from within the constructor to initialise the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        inMaxGen = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        inElitism = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        inRangeMin = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        inRunCount = new javax.swing.JSpinner();
        inRangeMax = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        inMutationChance = new javax.swing.JTextField();
        btnRun = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        inPopSize = new javax.swing.JSpinner();
        btnClear = new javax.swing.JButton();
        cbGenDetail = new javax.swing.JCheckBox();
        cbGenSummary = new javax.swing.JCheckBox();
        cbRunSummary = new javax.swing.JCheckBox();
        tbFitnessFunction = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cbSigmaScaling = new javax.swing.JCheckBox();
        inThreadCount = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        cbKnownMax = new javax.swing.JCheckBox();
        cbKnownMin = new javax.swing.JCheckBox();
        inMax = new javax.swing.JTextField();
        inMin = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbOutput = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        inMaxGen.setValue(10000);

        jLabel6.setText("Elitism");

        inElitism.setValue(1);

        jLabel7.setText("Range [");

        inRangeMin.setValue(1);

        jLabel8.setText(",");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Configure simulation");

        jLabel2.setText("Run count");

        inRunCount.setValue(1);

        inRangeMax.setValue(64);

        jLabel4.setText("Max Generations");

        jLabel9.setText("]");

        jLabel5.setText("Mutation Chance");

        inMutationChance.setText("0.01");

        btnRun.setText("Run Simulations");
        btnRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRunActionPerformed(evt);
            }
        });

        jLabel3.setText("Population Size");

        inPopSize.setValue(10);

        btnClear.setText("Clear Output");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        cbGenDetail.setText("Log evolutionary processes");

        cbGenSummary.setText("Log population each generation");

        cbRunSummary.setText("Log summary of each run");

        tbFitnessFunction.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        tbFitnessFunction.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tbFitnessFunction.setText("x*x");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Fitness Function:");

        cbSigmaScaling.setText("Sigma Scaling");

        inThreadCount.setValue(1);

        jLabel11.setText("Thread count");

        cbKnownMax.setSelected(true);
        cbKnownMax.setText("Known Maximum");
        cbKnownMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKnownMaxActionPerformed(evt);
            }
        });

        cbKnownMin.setText("Known Minimum");
        cbKnownMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKnownMinActionPerformed(evt);
            }
        });

        inMax.setText("4096");

        inMin.setText("0");
        inMin.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnClear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addGap(42, 42, 42)
                        .addComponent(inThreadCount, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(inMaxGen, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(inPopSize, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(inElitism, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(inMutationChance, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(inRunCount, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(tbFitnessFunction)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(cbGenDetail)
                            .addComponent(cbGenSummary)
                            .addComponent(cbRunSummary)
                            .addComponent(cbSigmaScaling)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inRangeMin, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inRangeMax, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9))
                            .addComponent(jLabel10))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbKnownMax)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inMax))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbKnownMin)
                        .addGap(6, 6, 6)
                        .addComponent(inMin)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inThreadCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inRunCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(inMaxGen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(inPopSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(inElitism, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(inMutationChance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(inRangeMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(inRangeMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbSigmaScaling)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbFitnessFunction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbKnownMax)
                    .addComponent(inMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbKnownMin)
                    .addComponent(inMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(cbGenDetail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbGenSummary)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbRunSummary)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRun)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClear)
                .addContainerGap())
        );

        tbOutput.setEditable(false);
        tbOutput.setColumns(20);
        tbOutput.setRows(5);
        jScrollPane1.setViewportView(tbOutput);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRunActionPerformed
        try {
            run();
        } catch (InterruptedException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRunActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        output.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void cbKnownMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKnownMaxActionPerformed
        inMax.setEnabled(cbKnownMax.isSelected());
    }//GEN-LAST:event_cbKnownMaxActionPerformed

    private void cbKnownMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKnownMinActionPerformed
        inMin.setEnabled(cbKnownMin.isSelected());
    }//GEN-LAST:event_cbKnownMinActionPerformed

/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
    public void run() {
        new GUI().setVisible(true);
    }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnRun;
    private javax.swing.JCheckBox cbGenDetail;
    private javax.swing.JCheckBox cbGenSummary;
    private javax.swing.JCheckBox cbKnownMax;
    private javax.swing.JCheckBox cbKnownMin;
    private javax.swing.JCheckBox cbRunSummary;
    private javax.swing.JCheckBox cbSigmaScaling;
    private javax.swing.JSpinner inElitism;
    private javax.swing.JTextField inMax;
    private javax.swing.JSpinner inMaxGen;
    private javax.swing.JTextField inMin;
    private javax.swing.JTextField inMutationChance;
    private javax.swing.JSpinner inPopSize;
    private javax.swing.JSpinner inRangeMax;
    private javax.swing.JSpinner inRangeMin;
    private javax.swing.JSpinner inRunCount;
    private javax.swing.JSpinner inThreadCount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tbFitnessFunction;
    private javax.swing.JTextArea tbOutput;
    // End of variables declaration//GEN-END:variables
}
